### ISSUE TITLE
datasource.json generated from cloudant connector comes with in memory connector

### ISSUE THREAD

**Issue by smartmouse** [strongloop/loopback-connector-cloudant#1]
steps to reproduce:
1.npm install -g strongloop-connector-cloudant
2.mkdir testLoopbackconnectorcloudant
3.cd testLoopbackconnectorcloudant
4.slc loopback
5.slc loopback:datasource

strongbot@plnx133:~/testLoopbackconnectorcloudant> slc loopback:datasource
? Enter the data-source name: cloudantdb
? Select the connector for cloudantdb: IBM Cloudant DB (supported by StrongLoop)

Then create model
slc loopback:model

 strongbot@plnx133:~/testLoopbackconnectorcloudant> slc loopback:model
? Enter the model name: cloudantmodel
? Select the data-source to attach cloudantmodel to: cloudantdb (cloudant)
? Select model's base class Model
? Expose cloudantmodel via the REST API? Yes
? Custom plural form (used to build REST URL): 
? Common model or server only? server

Afterwards,
in the datasources.json

you will see the following:
I am not sure why the db with memory connector is there. I never selected it and only
selected cloudant connector
  
  "db":
    "name": "db",
    "connector": "memory"
  },
  "cloudant": {
    "name": "cloudant",
    "connector": "cloudant"
  }

**Comment by chandadharap** [comment]
Not a bug. Close.

**Comment by krsyoung** [comment]
@chandadharap I have the same question as @smartmouse  ... if it isn't "Not a bug" what is it?  Is it used for something?
