### ISSUE TITLE
include filter broken

### ISSUE THREAD

**Issue by flam312** [strongloop/loopback-connector-cloudant#10]
looopback-connector-cloudant v1.0.6

When running any queries with a include filter the relation data returned is empty. While in debug mode I was able to get back the following error:

error": {

    "name": "Error",
    "status": ​500,
    "message": "function_clause",
    "error": "function_clause",
    "reason": null,
    "ref": ​1612317691,
    "scope": "couch",
    "statusCode": ​500,
    "request": 

{

    "method": "post",
    "headers": 

    {
        "content-type": "application/json",
        "accept": "application/json"
    },
    "uri": "https://XXXXXX:XXXXXX@flam312.cloudant.com/jenkins/_find",
    "body": "{\"selector\":{\"loopback__model__name\":\"LicenseFile\",\"packageId\":{\"$in\":[]}},\"use_index\":[\"lb-index-ddoc-LicenseFile\",\"lb-index-LicenseFile\"],\"sort\":[{\"id:string\":\"asc\"}]}"

}

My Package model hasMany LicenseFiles.

**Comment by tonyffrench** [comment]
$in is empty, can you share the query?

**Comment by flam312** [comment]
@tonyffrench 

Query: http://0.0.0.0:3000/api/packages?filter[where][id]=123&filter[include][hasLicense]
If I switch back to v1.0.5 the hasLicense field is populated otherwise it returns a empty array.

**Comment by tonyffrench** [comment]
@flam312 your right! I just crafted some additional include/relational tests and the previous change to support large queries needs to invoke fromDB before calling include() otherwise the id names are off. Working on a fix.

**Comment by flam312** [comment]
@tonyffrench thanks! I wasnt sure what the fromDB function did. now things are alot clearer.

**Comment by tonyffrench** [comment]
should be resolved with 1.0.7
