### ISSUE TITLE
Database isn't created automatically?

### ISSUE THREAD

**Issue by srl295** [strongloop/loopback-connector-cloudant#11]
Until I manually created the database in Cloudant, I got this error: 

> Error: Database does not exist

**Comment by tonyffrench** [comment]
The loopback-connector-mongo utilizes server side logic for db creation, cloudant/couch has no equivalent AFAIK. There is a consistency argument for updating this connector to automatically create the database.

**Comment by kjdelisle** [comment]
I wouldn't expect the connector to be responsible for creating databases on a user's behalf, especially since there's any number of reasons why that call is returning an error.
