### ISSUE TITLE
Upsert fails to create document when id provided, throws 404 NOT FOUND

### ISSUE THREAD

**Issue by djorg83** [strongloop/loopback-connector-cloudant#110]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

The create portion of upsert does not work if an id is supplied in the `data` argument.

Sample upsert call
```javascript
MyModel.upsert({
  myId: 'some-value',
  otherData: 'something'
});
```

Model definition
```json
{
  "name": "MyModel",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "myId": {
      "type": "string",
      "id": true,
      "required": true
    },
    "otherData": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

### Expected result

Document should be created if not found by id.

### Actual result (if bug)

404 is thrown.  Received error message: `No instance with id df97cbcd-8246-49ee-9354-599e8fe64e2f found for MyModel`

### Cause

This commit https://github.com/strongloop/loopback-connector-cloudant/commit/d5dd8c7834d3dd7244ac91e22cef88306b7fca15 caused the upsert to break.

### Additional information (Node.js version, LoopBack version, etc)
loopback-connector-cloudant: 1.2.2
Node Version: 6.0.0

**Comment by jannyHou** [comment]
Closing since https://github.com/strongloop/loopback-connector-cloudant/pull/129 merged
