### ISSUE TITLE
Backport options passthrough to 1.x

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-connector-cloudant#113]
connected to https://github.com/strongloop/loopback-connector-cloudant/issues/56

The options passthrough fix allows configuration of the lower-level drivers (nodejs-cloudant/nano), but is not a breaking API change. This fix has been asked for by members of the community.

**Comment by ssh24** [comment]
Backport has been released on `v1.2.3`. Closing the issue.
