### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#118]
## Feature

- discoverModelDefinitions
  - We can only discover modelName without properties
  - user should be able to provide custom modelSelector and map the design doc to a loopback model
- discoverSchemas
  - discover databases in a cloudant server

**Comment by jannyHou** [comment]
get all design docs: 
`GET /dbname/_all_docs?startkey="_design/"&endkey="_design0"&include_docs=true`

by api `db.list(opt, cb)`, provide the query in options according to https://github.com/apache/couchdb-nano/blob/master/lib/nano.js#L72

**Comment by kjdelisle** [comment]
This feature doesn't align with the more fundamental usage of CouchDB/Cloudant-like NoSQL databases. There is no inherent information that can be examined with certainty to decide which documents represent Models, or how many fields on a document represent the "minimum definition" of a Model.
