### ISSUE TITLE
Support for Design Functions

### ISSUE THREAD

**Issue by tverilytt** [strongloop/loopback-connector-cloudant#15]
Hi!
It would be very convenient to get support for CouchDB Design Functions (Map, Reduce...) in the loopback-connector-cloudant. Design Functions are core to CouchDB, and supporting them, will e.g. make it easier to switch between local CouchDB database, and Cloudant database in the cloud.

CouchDB documentation on Design Functions:
http://docs.couchdb.org/en/1.6.1/couchapp/ddocs.html?highlight=map%20reduce

With best regards
-jo2

**Comment by tonyffrench** [comment]
Using Cloudant Query vs CouchDB Views are two very different but equally important approaches. We have two choices: 1) enhance this connector to support MapReduce etc. 2) enhance https://github.com/mattange/loopback-connector-couch

IMO, given that the MapReduce approach is so different it would be cleaner to keep these implementations separate. 

Thoughts?

**Comment by jannyHou** [comment]
Hi @tonyffrench I am trying to support querying `view` in a loopback model, and come across problem when creating a `view` in a lb-model's design document.

When I read your comments above I think maybe you could share more insight here, any help or clue are appreciated :)

Now the `index` is created with `type=text`(to support cloudant query), and the design doc of the `index` has `language: 'query'` by default, which throws error when I try to save a `view` with String type map function, so my question is:

- Can I specify other design doc languages when creating a text type index? Or it only supports language 'query'?

- If language 'query' is the only choice, is it possible to create a view with object type value of `map`, which can still be interpreted as a map function?

I searched through the cloduant&couchdb document, but find very few explanations regarding these.

Thanks in advance!

**Comment by kjdelisle** [comment]
Closing this. See #67 for progress on this item.
