### ISSUE TITLE
Support disabling all_index

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-connector-cloudant#167]
We force the `all_fields` in order to support mongodb style dynamic object querying - without specifying an index for each property. This makes it hard / impossible to optimize your usage of the connector though.

This issue is for tracking a new feature:

 - being able to disable `all_fields` via configuration
 - being able to manually opt into index for each property that should be indexable

**Comment by akshaysin** [comment]
+1

**Comment by jannyHou** [comment]
The feature is released in version 2.x

**Comment by NilsITO** [comment]
Is it somewhere documented?
I added "index":true to the model property but there seems to be no effect. In fact I think all_fields must somehow be manually disabled?
