### ISSUE TITLE
Could not found minus value.

### ISSUE THREAD

**Issue by knoro** [strongloop/loopback-connector-cloudant#17]
Hi.

I tried found at cloudant data, but could not found minus value data.

  success: lat = 90
  failed: lat = -90

How to find the minus value data ?

source: --databasename--.js

```
.
--databasename--.find({"where":{"and":[{"lat":-90}]}},function(err, result) {
            if (err) {
                console.log("--- error ---";
            } else {
                console.log("---  lng: ",  result.lng);
            }
}
.
```

model.properties: --databasename--.json

```
.
  "properties": {
    "_id": {
      "type": "string",
      "id": 1
    },
    "_rev": {
      "type": "string"
    },
    "timestamp": {
      "type": "date"
    },
    "lat": {
      "type": "number"
    }
}
.
```

cloudant data:

```
{
  "_id": "{any_id}",
  "_rev": "{any_rev}",
  "timestamp": "2016-05-12T06:00:00Z",
  "lat": -90
  "lng": 130
}
,
{
  "_id": "{any_id}",
  "_rev": "{any_rev}",
  "timestamp": "2016-05-12T06:00:00Z",
  "lat": 90
  "lng": 135
}
```

I tried in cloudant query box , but also could not found.

query:

```
{
  "selector": {
    "loopback__model__name": "--databacename--",
    "lat": -90
  },
  "fields": ["_id", "_rev",  "lat", "lng" ]
}
```

**Comment by dhmlau** [comment]
@virkt25  could you please take a look? thanks.

**Comment by jannyHou** [comment]
I think it's a bug on Cloudant side, the Cloudant query only takes in JSON format query, then Cloudant query parser converts it to Lucene syntax query, while seems the parser doesn't handle minus value properly(e.g. escape dash)

**Comment by jannyHou** [comment]
ah, the latest release of [Cloudant Local docker@3](https://hub.docker.com/r/ibmcom/cloudant-developer/) fixes the problem.

<img width="1071" alt="screen shot 2017-06-12 at 2 44 24 pm" src="https://user-images.githubusercontent.com/12554153/27049554-af617686-4f7d-11e7-9d60-b03c04561d7c.png">

Please make sure you update to the latest Cloudant version.
