### ISSUE TITLE
Update of the connector to Version 2.0.2 breaks connection

### ISSUE THREAD

**Issue by sebastiansutter** [strongloop/loopback-connector-cloudant#175]
I had a working demo in APIC with the loopback connector just before version 2.0.2 got released. When I updated the connector from version 1.2.5 to version 2.0.2, the connection from the data source in APIC Designer is no longer possible.

Steps to reproduce:
create a new loopback project on commandline: apic loopback
open api designer: apic edit
Got to Data Models and create a Cloudant Data Source. Press the link to install the connector

Paste a connection URL and hit save

# Expected result
Data source connection test succeeded

# Actual result
Data Source Connection Failed 
undefined
Data source connection test failed with error: Cannot read property 'db' of undefined

**Comment by jannyHou** [comment]
@sebastiansutter I think I know why it fails, cloudant@1.x sometimes runs into a bug that executes functions before connection established and a valid driver instance get returned. To fix it, in cloudant@2.x we listen on the `connected` event when establishing a connection, for example, if your cloudant@1.x code is written in this way:
```js
cloudantDS.ping(function(err) {
   // Do stuff
});
```
In cloudant@2.x you need to rewrite the function to: 
```js
cloudantDS.once('connected', function() {
  cloudantDS.ping(function(err) {
     // Do stuff
  });
});
```

API designer calls the `ping` function without waiting until `connected`, which means this needs to happen inside connector's `ping` function.
We will fix it asap whenever we have time.

**Comment by jannyHou** [comment]
should be fixed in https://github.com/strongloop/loopback-connector-cloudant/commit/b59747cc36709d97087ded502f63ed3044b7856b

**Comment by dhmlau** [comment]
Version 2.0.3. has been released.  Closing this issue.
