### ISSUE TITLE
Update to 2.0.2 breaks modelIndex

### ISSUE THREAD

**Issue by fizzl** [strongloop/loopback-connector-cloudant#176]
# Description/Steps to reproduce
I was updating my API from loopback 2.x to 3.x. I also updated loopback-connector-cloudant to 2.x.
After I had resolved all other issues, my last problem is that when I try to use my application, my first API query fails with:

```
Unhandled error for request GET /api/csp/sites?filter=%7B%22where%22:%7B%22name%22:%7B%22regexp%22:%22%2Ffoo%2Fi%22%7D%7D,%22order%22:%22name+DESC%22,%22limit%22:10%7D: Error: You must specify an index with the `use_index` parameter.
    at Request._callback (D:\Src\KONE\DCT\api\node_modules\cloudant-nano\lib\nano.js:248:15)
    at Request.self.callback (D:\Src\KONE\DCT\api\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\Src\KONE\DCT\api\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\Src\KONE\DCT\api\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```
In my datasouce config I have:
`modelIndex: 'modelIndex'
`
I also tried configuring indexes separately for said model, without success.

Rolling back to 1.2.5 fixed the problem.

# Link to reproduction sandbox

I don't have spare VM instances just laying around.

> Note: Failure to provide a sandbox application for reproduction purposes will result in the issue being closed.

Well, that's a bit hostile. 

# Expected result

Old models with old indexes continue to work.

# Additional information

win32 x64 6.10.1

```
+-- loopback@3.11.1
+-- loopback-boot@3.0.1
+-- loopback-component-explorer@4.2.0
+-- loopback-component-passport@3.4.1
+-- loopback-connector-cloudant@2.0.2
```

**Comment by jannyHou** [comment]
@fizzl you don't need to provide a vm, just leave the datasource config empty in https://github.com/strongloop/loopback-sandbox I can test with my local instance.

By your description I don't know how to reproduce the error...the new connector doesn't inject an `use_index` field in query unless you provide it.

**Comment by fizzl** [comment]
I'll check tomorrow if I can find out what I did to remedy this situation. I doing pretty complicated dependency upgrade and this was one of the issues. I got it solved somehow but I cannot remember how exactly from the top of my head.

I'll try to provide more details soon.

**Comment by jannyHou** [comment]
@fizzl I just had a chat with other user and see the same problem.
I still have no idea why it happens, it fails when the user uses a connector@2.x with the design docs created with connector@1.x.

But if you restart your app with connector@2.x from scratch, create a new database, run `autoupdate` for your datasource, the bug disappears. 

Will update more details after I figure out the reason.
