### ISSUE TITLE
Out dated / error in dependancies

### ISSUE THREAD

**Issue by Danwakeem** [strongloop/loopback-connector-cloudant#185]
# Description
There seems to be an issue with the current version of Cloudant listed in this packages dependancies. 

I have [forked this repo](https://github.com/Danwakeem/loopback-connector-cloudant) and updated the Cloudant package to the new version (1.10.0-NOTICE), ran `npm test` and that seemed to be a valid fix but I just wanted to open a issue before submitting a PR just incase you guys were already aware or had other plans to address this issue.

![screen shot 2018-02-14 at 3 54 44 pm](https://user-images.githubusercontent.com/1753824/36230987-f6f89b0a-11a1-11e8-996c-5c74bdf772f0.png)

**Comment by dhmlau** [comment]
@Danwakeem , #186 has landed.  Is it good to close?  Thanks.

**Comment by Danwakeem** [comment]
Oh yeah definitely @dhmlau
