### ISSUE TITLE
Count returns a max of 25

### ISSUE THREAD

**Issue by renezuidhof** [strongloop/loopback-connector-cloudant#188]
When we request the Count method in our Loopback model it never returns anything higher then 25. There are more then 25 items in the database (tested by calling Find with a limit of 100).

Does anyone know why this happens or what I can do to further investigate this issue? Below is more information.

We are running a docker image (ibmcom/cloudant-developer:2.0.1) which we use as the database for Loopback (3.8.0).

Below is the request that is being sent together with its result.

Request
![screen shot 2018-03-08 at 17 47 07](https://user-images.githubusercontent.com/522888/37357632-3c8d9506-26e9-11e8-9610-6fc03b224656.png)
Response
![screen shot 2018-03-08 at 17 47 16](https://user-images.githubusercontent.com/522888/37357633-3ca9c578-26e9-11e8-9c1b-e2b38346d17e.png)

The AddressBookEntry model enables the count method as follows:
```
{
  "name": "addressBookEntry",
  "plural": "addressBookEntries",
  "base": "address",
  "idInjection": true,
  "mixins": {
    "SetupRemoteMethods": {
      "disableAllExcept": [
        "count"
      ]
    }
  }
  ...
}
```

**Comment by dhmlau** [comment]
@renezuidhof , it seems to be fixed in `loopback-connector-couchdb2@1.2.0` which the cloudant connector depends on.  Could you please which version of `loopback-connector-couchdb2` you're using? Thanks.

**Comment by renezuidhof** [comment]
We are currently using loopback-connector-couch2db 1.1.0. Thanks for the tip, I will update to see if the bug is fixed.

**Comment by renezuidhof** [comment]
Turns out the fix in 1.2.0 adds a global limit. If that global limit is not set the default limit of couchdb (default = 25) is still used. So count still only returns a max of 25.

We will try to see if we can work around this issue.

**Comment by dhmlau** [comment]
You can set the limit at the top level of the datasources.json. e.g. 
`globalLimit: 100`

**Comment by renezuidhof** [comment]
Do you have an example of where exactly to set it?
