### ISSUE TITLE
Add support Geospatial queries

### ISSUE THREAD

**Issue by Danwakeem** [strongloop/loopback-connector-cloudant#190]
# Description
Add Geospatial query mixin. It would be nice if it worked the same as the `viewDocs` mixin.

# Expected result
`db.connector.geoDocs(ddocName, viewName, options, cb);` 
should return the results from [`db.geo()`](https://github.com/cloudant/nodejs-cloudant#cloudant-geospatial).

**Comment by virkt25** [comment]
Are you referring to something like this https://github.com/strongloop/loopback-connector-cloudant/pull/191

**Comment by Danwakeem** [comment]
Yes, I am the one who opened that PR. I wasn’t sure if the maintainers would want me to open an issue along with a PR or not so I went ahead and did both.

**Comment by dhmlau** [comment]
@Danwakeem , I'm moving this issue to `In Progress` to reflect the current status.

**Comment by Danwakeem** [comment]
Hey @dhmlau this was merged into master today so I will go ahead and close this out. Thank you again!

**Comment by dhmlau** [comment]
Thanks! We just released `2.1.0` to include this change.
