### ISSUE TITLE
Update driver to nodejs/cloudant

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#215]
See parent spike story https://github.com/strongloop/loopback-connector-cloudant/issues/214

### Acceptance Criteria 

- [ ] Update driver to https://github.com/cloudant/nodejs-cloudant
- [ ] Find a new db (support partition)for test
    - The docker one is retired and don't support partition
    - Check the couchdb2 image as well, and replace it with a new one if necessary. (since 95% of the code are written in loopback-connector-couchdb2)

**Comment by jannyHou** [comment]
The new docker image: https://hub.docker.com/r/ibmcom/couchdb3

**Comment by emonddr** [comment]
@jannyHou have you submitted a PR for this yet? Is this possible for October?

**Comment by jannyHou** [comment]
@emonddr I have code change on local, haven't created the PR. I see a PR updating the docker image https://github.com/strongloop/loopback-connector-cloudant/pull/223#pullrequestreview-303991999, it would be better if we can upgrade to use https://hub.docker.com/r/ibmcom/couchdb3.

**Comment by emonddr** [comment]
> #223 (review)

@agnes512  closed this PR after we had a discussion, and she realized it wasn't needed.

**Comment by jannyHou** [comment]
closed as https://github.com/strongloop/loopback-connector-cloudant/pull/224 landed
