### ISSUE TITLE
findAll: Read partitionKey from `options`

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#220]
See parent story: https://github.com/strongloop/loopback-connector-cloudant/issues/214

## Acceptance Criteria

- [x] For method `Couchdb2.prototype.all()`(which maps to model method `find`), get the partition key from `options` like: 
  ```js
   Customer.find({
      where: { name: 'somename' }
   },
   {
      // options
      partitonKey: 'US'
   });
   ```
   If `partitionKey` is found, then invoke `driverInst.partitionedFind(partitionKey, query)` to find documents.

**Comment by raymondfeng** [comment]
It should be `{cloudant: {partitionKey: 'US'}}` or `{partitionKey: 'US'}`.

**Comment by jannyHou** [comment]
Closing since PR merged
