### ISSUE TITLE
Invalid key partitioned using with Cloudant docker locally

### ISSUE THREAD

**Issue by sinny777** [strongloop/loopback-connector-cloudant#238]
I'm using Loopback 4 and trying to run migrate option.  When using local docker image of Cloudant (ibmcom/cloudant-developer), it throws following error:

'Invalid key partitioned for this request.'

However, it works fine with Cloudant instance on IBM public cloud.

Here's the full error message:

name: 'Error',
  error: 'invalid_key',
  reason: 'Invalid key partitioned for this request.',
  scope: 'couch',
  statusCode: 400,
  request: {
    method: 'post',
    headers: { 'content-type': 'application/json', accept: 'application/json' },
    uri: 'http://XXXXXX:XXXXXX@localhost:8888/auth-clients/_index',
    body: '{"index":{"fields":[{"loopback__model__name":"asc"}]},"partitioned":false,"ddoc":"LBModel__auth_clients__LBIndex__loopback__model__name_index","name":"loopback__model__name_index","type":"json"}',
    qsStringifyOptions: { arrayFormat: 'repeat' }
  },
  headers: {
    uri: 'http://XXXXXX:XXXXXX@localhost:8888/auth-clients/_index',
    statusCode: 400,
    'cache-control': 'must-revalidate',
    'content-type': 'application/json',
    date: 'Wed, 05 Feb 2020 11:34:54 GMT',
    'x-couch-request-id': '169749e8da',
    'x-couchdb-body-time': '0'
  },
  errid: 'non_200',
  description: 'couch returned 400'

**Comment by agnes512** [comment]
@jannyHou could you take a look of this issue? thanks.

**Comment by dhmlau** [comment]
@sinny777, could you please provide more details in reproducing this problem? e.g. the models you used for database migration. Thanks.

**Comment by sinny777** [comment]
@dhmlau , this is the issue with all the models and the reason seems to be the cloudant docker image is too old and is not upgraded to use "partitioned" database feature.  My same code works when using the "migrate" option with Cloudant instance on IBM public cloud, but when I change it use local cloudant docker container, it throws the error.

I'm using Loopback 4 and am using loopback-connector-cloudant@2.4.0.  If you see the error message it says Invalid key "partitioned" which doesn't seem to be supported by local cloudant docker image.

For your reference, attaching here one of the models:
[auth-client.model.txt](https://github.com/strongloop/loopback-connector-cloudant/files/4163278/auth-client.model.txt)

Thanks for looking into this and please let me know if you need more information.

**Comment by jannyHou** [comment]
@agnes512 (Thank you!)recently updated the setup script and documented in https://github.com/strongloop/loopback-connector-cloudant#docker, can you try the new docker image? It works on my local.

**Comment by jannyHou** [comment]
I am closing this issue since the new setup steps are updated in https://github.com/strongloop/loopback-connector-cloudant#docker.

Feel free to reopen it if you still have problems. Thanks for understanding.
