### ISSUE TITLE
Regex query does not obey ignoreCase flag

### ISSUE THREAD

**Issue by tanndev** [strongloop/loopback-connector-cloudant#25]
I'm making a query through the Cloudant connector with a filter that looks like this:
```
{where: {name: {regexp: '/Foo/i'}}}
```

I've narrowed down the problem to the following lines: (Starts at 329, for me, in cloudant.js.)
```Node
if (cond.constructor.name === 'RegExp') {
    if (cond.global)
        console.warn('Cloudant regex syntax does not support global');
    query[k] = {$regex: cond.source};
} else {
    query[k] = {$regex: cond};
}
```

At the start of the code, my `cond` object is as follows:
```JSON
{
"global": false,
"ignoreCase": true,
"multiline": false,
"source": "Foo"
}
```

As a RegExp object, it drops into the first if and builds the query with
`query[k] = {$regex: cond.source}`
and thus ignores the ignoreCase and multiline flags.

I'll submit a pull request shortly with a fix.

**Comment by superkhau** [comment]
Closing as this has been resolved by #26
