### ISSUE TITLE
Backport ESLint fixes to loopback-2.x

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-connector-cloudant#41]
# Steps to reproduce

```
git checkout loopback-2.x
# refresh node_modules
npm test
```

**Comment by dhmlau** [comment]
It's completed in this commit.  https://github.com/strongloop/loopback-connector-cloudant/commit/eaa0a68ebd206ab1b86a29b2c0df3162cfee0396 
Closing it.
