### ISSUE TITLE
Release 1.1.0 seems to have broken the upsert

### ISSUE THREAD

**Issue by jmereaux** [strongloop/loopback-connector-cloudant#43]
Hi,

When using the latest release 1.1.0, seems like attempting an upsert of an instance that is not yet in the database gives a 404.
Reverting to 1.0.11 fix the issue.

Could you please take a look?
Thanks

**Comment by jannyHou** [comment]
@jmereaux Thank you for catching the bug, I will take a look asap.

**Comment by jannyHou** [comment]
@jmereaux I verified with loopback-connector-cloudant@1.1.0 and the latest version @1.2.2, `upsert` works for both of them.

1. create a cloudant ds
2. create a model attach it to that ds
3. create a bootScript: 
  ```js
  'use strict';

module.exports = function(server) {
  var Test = server.models.Test;
  Test.upsert({name: 'hehe'}, function(err, result) {
    console.log(err, result);
  });
};
  ```

4. `node .` and you will see it works.

If you still run into this error, could you fork https://github.com/strongloop/loopback-sandbox and provide me your code? Thanks! 
And please specify which version of `loopback-datasource-juggler` and `loopback-connector` you use.

**Comment by jmereaux** [comment]
@jannyHou I've just tested with the latest version @1.2.2.
Still running into the issue.
Could it be linked to the fact that the model instance I'm trying to upsert has a custom id:

"email": {
      "type": "string",
      "id": true,
      "required": true
}

**Comment by kjdelisle** [comment]
@jmereaux Hello again! Would you be able to provide a reproduction using a fork of [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) as a base?
Thank you!

**Comment by jannyHou** [comment]
@kjdelisle I think it's same as https://github.com/strongloop/loopback-connector-cloudant/pull/111

**Comment by jannyHou** [comment]
I am closing this one as a dup of #111 , let's keep discussion there. Thank you @jmereaux for catching it.
