### ISSUE TITLE
updateAll doesn't replace the property with array type. 

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#44]
Reproduce:
1. Create a model `Test`
2. Create an instance for `Test`:
   
   ``` js
   testInstance: {
     id: 1,
     name: 'test1'
     skills: [
       {id: 0, text: "JAVA"},
       {id: 1, text: "CSS"},
       {id: 2, text: "HTML" },
       {id: 3, text: "JAVASCRIPT"},
       {id: 4, text: ".NET"}
     ]
   }
   ```
3. Try updateAll:
   
   ``` js
   Test.updateAll({id: test.id}, {skills: [
   { id: 1, text: "newJAVA"},
   { id: 2, text: "newCSS"}
   ]}, function(err, count){} );
   ```
4. The updated skills are expected to be:
   
   ``` js
    skills: [
      { id: 1, text: "newJAVA"},
      { id: 2, text: "newCSS"}
    ]
   ```
   
   But actual result is:
   
   ``` js
   skills: [
     {id: 0, text: "newJAVA"},
     {id: 1, text: "newCSS"},
     {id: 2, text: "HTML" },
     {id: 3, text: "JAVASCRIPT"},
     {id: 4, text: ".NET"}
   ]
   ```

Details see: http://stackoverflow.com/questions/40111147/updateall-loopback-datasource-does-not-delete-deletions-inside-updated-data

**Comment by gunjpan** [comment]
@jannyHou : Same issue as: https://github.com/strongloop/loopback-connector-cloudant/issues/47#issuecomment-274858304

Root cause: https://github.com/strongloop/loopback-connector-cloudant/blob/35580d0df5ce322f194e3c5b606e4230965ae021/lib/cloudant.js#L574

**Comment by jannyHou** [comment]
I think it's already fixed in https://github.com/strongloop/loopback-connector-cloudant/pull/117, closing it. Feel free to reopen it if you still run into same error.
