### ISSUE TITLE
updateAttributes doesn't replace the property with array type.

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#47]
#Same problem as `updateAll`: https://github.com/strongloop/loopback-connector-cloudant/issues/44

Reproduce:

A model instance with an array type property

``` js
  modelInstance: {
     name: 'test',
     arrProperty: [
       {id: 1, name: original1},
       {id: 2, name: original2},
       {id: 3, name: original3}
     ] 
  }
```

When do updateAttributes:

``` js
modelInstance.updateAttributes({arrProperty: [
  {id: 1, name: new1},
]})
```

The expected new arrProperty is 

``` js
arrProperty: [{id: 1, name: new1}]
```

But actual result is

``` js
arrProperty: [
       {id: 1, name: new1},
       {id: 2, name: original2},
       {id: 3, name: original3}
     ] 
```

**Comment by rimvydas-urbonas** [comment]
What is the status of this issue?

**Comment by jannyHou** [comment]
@rimvydas-urbonas We label the issue as "Needs Priority" but it's not in backlog yet :(

**Comment by rimvydas-urbonas** [comment]
Maybe you can suggest workaround to update array property by replacing value not appending?
Thanks in advance.

**Comment by kjdelisle** [comment]
Being unable to update array properties seems fairly major to me. Going to add this to our backlog.

**Comment by gunjpan** [comment]
@jannyHou : The root cause for this issue is `_.merge()` at [lib/cloudant.js : L517](https://github.com/strongloop/loopback-connector-cloudant/blob/35580d0df5ce322f194e3c5b606e4230965ae021/lib/cloudant.js#L517). This should be replaced with `_.mergeWith(object, sources, customizer)` where `customizer` is the function to handle Arrays. See more [here](https://lodash.com/docs/#mergeWith)

**Comment by jannyHou** [comment]
I think it's already fixed in https://github.com/strongloop/loopback-connector-cloudant/pull/117, closing it. Feel free to reopen it if you still run into same error.
