### ISSUE TITLE
AssertionError: url is not valid

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-cloudant#5]
When the data-source configuration does not provide all required settings, the connector initialisation fails with `AssertionError: url is not valid`. This error message is misleading - it hints that the `url` setting is required, which is not true.

Please improve the code building settings for `cloundant` driver ([source code](https://github.com/strongloop/loopback-connector-cloudant/blob/4798b843ea501a0f0ac5bff7319827766e87c0f4/lib/cloudant.js#L32-L35)) to verify that the configuration is valid and report a helpful error message otherwise.

/cc @ritch @raymondfeng

**Comment by tonyffrench** [comment]
fixed with commit a67cfcb
