### ISSUE TITLE
Keep ._rev property on returned instance of model

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#55]
A further discussion of https://github.com/strongloop/loopback-connector-cloudant/pull/54#issuecomment-259401952
Regarding
> When I step back a bit and look at the problem from a high level perspective, then I think it should be acceptable to require callers of patch/replace operations to provide _rev in the data, as that's the way how CouchDB/Cloudant allows clients to detect and resolve conflicts

Our current implementation:
Now whenever `rev` is needed, eg: in function `Cloudant.prototype.delete()`, `Cloudant.prototype.replaceById()`, we call `getCurrentRevision()`.
But considering the nature of Cloudant db, we should ask the caller to provide `rev`, and return error if it's missing.

Affected functions:
  - updateOrCreate
    - PATCH Models/
    - Provide rev when updating an existed instance with `data: {rev: rev_of_new_data} `
  - replaceOrCreate
    - PUT Models/
    - Provide rev when replacing an existed instance with `data: {rev: rev_of_new_data} `
  - save
    - need to investigate
  - replaceById
    - Provide rev when replacing an existed instance with `data: {rev: rev_of_new_data} `
  - delete
    - DELETE Models/
    - We disabled this endpoint and DELETE Models/{id} doesn't accept data...any idea? Probably keep our current design.

**Comment by bajtos** [comment]
> But considering the nature of Cloudant db, we should ask the caller to provide rev, and return error if it's missing.

A big +1 from me.

I believe the field is called `_rev` in Cloudant, isn't it? https://docs.cloudant.com/mvcc.html#revisions

I am proposing to define a `_rev` property on a model at the time when the model is attached to a Cloudant datasource. That way the `_rev` property will be propagated to Swagger too.

The catch is how to tell clients that `_rev` should not be included in `create` requests? This is similar to the problem of excluding `id` property when `forceId` is `true`, see https://github.com/strongloop/loopback/issues/2924

**Comment by jannyHou** [comment]
@bajtos ah sorry I forgot to direct you to https://github.com/strongloop/loopback-connector-cloudant/pull/54#issuecomment-260415145, I made some comment about how to let callers access `_rev` in that link. 

> The catch is how to tell clients that _rev should not be included in create requests

True, my suggestion is based on using a option flag to tell function `fromDB()` returns `_rev` with data or not.

**Comment by kjdelisle** [comment]
@ssh24 What's left for this task:
- Ensure `_.rev` is not being altered on any of the remaining CRUD methods. The PR in its current state has replaceOrCreate, updateOrCreate and create covered (with tests). You'll probably need to make sure that all of the find and destroy functions also respect it.
- You'll also need to demonstrate that they work across the REST APIs; that is, it should show the `_.rev` property in the returned payloads on GET, and should accept (and use) `_.rev` on POST/PUT/PATCH/DELETE

**Comment by ssh24** [comment]
The feature has been landed and awaiting to be released on the next major version. Closing this ticket as a result.
