### ISSUE TITLE
Rate limits from new IBM Bluemix Cloudant plans are not managed by the connector

### ISSUE THREAD

**Issue by l2fprod** [strongloop/loopback-connector-cloudant#56]
Cloudant in Bluemix has plans with rate limits. It used to have a "Shared" plan with a limit of storage but the new plans have introduced read and write per second limits:
https://www.ibm.com/blogs/bluemix/2016/09/new-cloudant-lite-standard-plans-are-live-in-bluemix-public/

The Cloudant nodejs package has been updated to cope with the new limits and automatically retry. This is implemented with a Cloudant "retry" plugin:
https://github.com/cloudant/nodejs-cloudant#request-plugins

The loopback-connnector-cloudant should be updated to use the latest Cloudant nodejs package and support the configuration of the retry plugin.

Typically I'm getting http error 429 (the Cloudant error code when you reach the rate limit) and messages like:

```
Error: You've exceeded your current limit of 5 requests per second for query class. Please try later.
    at Request._callback (/Users/fred/dev/api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/Users/fred/dev/api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/fred/dev/api/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/fred/dev/api/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
```

**Comment by l2fprod** [comment]
I tried a local fix https://github.com/l2fprod/loopback-connector-cloudant/commit/f342236322aa0f959d9a423a8238387c8ba4c8c7 enabling the retry plugin and obviously it solves the issue. Ideally this should be built-in into the connector with configuration from the datasource.

**Comment by xpqz** [comment]
It would be great if StrongLoop's Cloudant connector could wrap Cloudant's nodejs library. The Shared plan has been deprecated in favour of the new rate-capped Lite & Standard plans, and at the moment SL dies when used against the Lite plan. The Lite plan is intended to serve as a free-forever taster/development tier but applications using that need to be mindful of the caps. Cloudant's library has configurable backoff&retry handling through its `retry` plugin. 

Stefan Kruger, IBM Cloudant.

**Comment by superkhau** [comment]
@xpqz Thanks for the feedback, this is definitely something we should take into consideration. @jannyHou We should add this to your connector's roadmap doc.

**Comment by kjdelisle** [comment]
It seems like this issue is actually about not supporting plugin configuration in the connector; we're not passing through an options object that allows configuration of the nodejs-cloudant module.
https://github.com/strongloop/loopback-connector-cloudant/blob/master/lib/cloudant.js#L56
cc @superkhau @jannyHou

**Comment by l2fprod** [comment]
@kjdelisle you're right. I've a straightforward fix https://github.com/l2fprod/loopback-connector-cloudant/commit/f342236322aa0f959d9a423a8238387c8ba4c8c7 for my own app but would love to see plugin support built in the connector!

**Comment by kjdelisle** [comment]
I've merged the passthrough into the master stream, and it should be a part of the connector's 3.0.0 release when that time comes.

**Comment by bluemixgarage** [comment]
Hi, do we have an idea when the 3.0.0 will be released?

**Comment by patsvc** [comment]
Any plans to port this to the LTS release? We would really like to have this fix because we keep hitting these limits.

**Comment by kjdelisle** [comment]
@patsvc I'll add this to our backlog. It's not a breaking change, so I imagine it wouldn't be too much work.

**Comment by ssh24** [comment]
This should be released on `v1.2.3`

**Comment by jmereaux** [comment]
Hi, still running into this issue after upgrading to `1.2.3` and adding the following to my datasource config:
`'plugin':` 'retry',
'retryAttempts': 5,
'retryTimeout': 1000`

Any advice?

**Comment by jannyHou** [comment]
@jmereaux  Is your model a `User` model or just a regular persistedModel? And which cloudant server are you using? A bluemix one or docker one or?

**Comment by jmereaux** [comment]
@jannyHou It is a regular PersistedModel. I'm using a Cloudant server on Bluemix (standard plan = 100 lookups/s, 50 writes/s, 5 queries/s)
