### ISSUE TITLE
too many boolean clauses error on large include query

### ISSUE THREAD

**Issue by flam312** [strongloop/loopback-connector-cloudant#6]
The fix in #3 allowed queries to return results > 200 from the connector. However, now I am getting a "too many boolean clauses" error when returning my results. 

Context: I am running two queries. The first finds the total count of a particular package model (2k+ results). This returns fine without any problems. My second query has a include filter to tie in another relation to the package instances and this is where I get the error. It looks like the problem is with the query containing a $in field of the array of package ids which is over the boolean clauses limit. 

Further looking at the code in lib/cloudant.js it looks like the include query is ran on the total docs returned. Would running the include query on each 200 page bookmark solve this issue?

@tonyffrench your thoughts? Also thanks for all the help in the previous issue!

**Comment by tonyffrench** [comment]
I have a reproduction, taking a look now.
