### ISSUE TITLE
Support to query view

### ISSUE THREAD

**Issue by xi4oc4i** [strongloop/loopback-connector-cloudant#67]
### Bug or feature request

- [ ] Bug
- [x ] Feature request

### Description of feature (or steps to reproduce if bug)

Couch connector supports to query the view, will cloudant connector support this feature?

https://www.npmjs.com/package/loopback-connector-couch

**Comment by dhmlau** [comment]
@raymondfeng, any thought on supporting query on view (or search indexes) for Cloudant connector?

**Comment by jannyHou** [comment]
query view would be a cloudant specific function, it will be good if we can define it in cloudant connector, like:
```
// in `lib/cloudant.js`
Cloudant.prototype.queryView() {
 // code
}
```
then in juggler `lib/datasource.js`, we can mix certain connector specific functions to Model, like how we mix DAO functions to model in https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L585

This would also be useful across all connectors.
@raymondfeng Any thought?

**Comment by dhmlau** [comment]
@jannyHou @raymondfeng , I think it's a good idea to have a consistent story in supporting views across connectors because they are not specific to Cloudant.  

Similar question in mssql: https://github.com/strongloop/loopback-connector-mssql/issues/26

**Comment by jannyHou** [comment]
- [db.view(designname, viewname, [params], [callback])](https://github.com/apache/couchdb-nano#dbviewdesignname-viewname-params-callback)
  - This is the main function exported by nano to query view.
  - If our goal is to support it, we can define a method `Cloudant.prototype.view(viewname, [params], cb)`, `designname` can be read from loopback model name, `viewname` and `params` are inputs.

**Comment by jannyHou** [comment]
Turns our the `view` could not be a model level api with current design, explained in https://github.com/strongloop/loopback-connector-cloudant/issues/15#issuecomment-300955117


Other plans:

- strategy1: Support those design functions like view as datasource level functions, so a view don't need to be created in a lb-model's design doc.
- srategy2: Use two design docs(one for index one for view) to represent a loopback model.

**Comment by b-admike** [comment]
Steps taken to verify:

- Create a DDoc on cloudant db called `TestViewDDoc` with a view `hadtraining`
```json
{
  "_id": "_design/TestViewDDoc",
  "_rev": "13-2738c014de2d5b6cfc02522d1bdc45fc",
  "views": {
    "hadtraining": {
      "map": "function(doc) {\n    if (doc.training) {\n        emit(doc.number, doc.training);\n    }\n}"
    }
  }
}
```
- Create some docs which satisfy the view criteria
- Add boot script to a test LB app which is connected to the same cloudant db and queries for the view:
```javascript
module.exports = function(app) {
  var ds = app.dataSources.cldntlocal;
  ds.on('connected', function() {
    // 1. Please note `ds.connector.viewDocs()` is the correct way to call it,
    // NOT `ds.viewDocs()`
    // 2. This api matches the Cloudant endpoint:
    // GET /db/_design/<design-doc>/_view/<view-name>
    ds.connector.viewDocs('TestViewDDoc', 'hadtraining', function(err, results, rows) {
      // `results` would be the data returned by quering that view
      console.log('view total rows ', results.total_rows);
      console.log('view results ', results.rows);
    });
        // Alternatively user can also specify the filter for view query
    ds.connector.viewDocs('TestViewDDoc', 'hadtraining', {key: 5},
      function(err, results) {
        console.log('view by filter total rows ', results.total_rows);
        console.log('view by filter results ', results.rows);
      });
  });
};
```

Results:
```shell
| => node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
view by filter total rows  4
view by filter results  [ { id: '6d8d81bff8f54ccd35f499bc3e0799e8',
    key: 5,
    value: '10/02/2012' } ]
view total rows  4
view results  [ { id: '6d8d81bff8f54ccd35f499bc3e03fe6c',
    key: 1,
    value: '12/20/2011' },
  { id: '6d8d81bff8f54ccd35f499bc3e0410f4',
    key: 1,
    value: '12/20/2011' },
  { id: '6d8d81bff8f54ccd35f499bc3e079366',
    key: 3,
    value: '12/05/2013' },
  { id: '6d8d81bff8f54ccd35f499bc3e0799e8',
    key: 5,
    value: '10/02/2012' } ]
^C
```
Thanks @jannyHou for your help!

**Comment by b-admike** [comment]
connect to https://github.com/strongloop-internal/scrum-apex/issues/240
