### ISSUE TITLE
How to find all instances of a model which have their "belongsTo" relation unset

### ISSUE THREAD

**Issue by jmereaux** [strongloop/loopback-connector-cloudant#7]
Hi,

Not sure this is really an issue, maybe I just don't know the right way of doing things...
Let's take the following example with two models Person and Vehicle:

```
{
  "name": "Person",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "name",
      "required": true
    },
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

{
  "name": "Vehicle",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
  },
  "validations": [],
  "relations": {
    "owner": {
      "type": "belongsTo",
      "model": "Person"
    },
  },
  "acls": [],
  "methods": {}
}
```

Is there any simple query to perform in order to fetch all vehicles that don't have an owner?

Would it be possible to do anything like one of the lines below?
Vehicle.find({where: {personId: null}})
Vehicle.find({where: {personId: undefined}})
Vehicle.find({where: {owner: {exist:false}}})

**Comment by tonyffrench** [comment]
@raymondfeng: ideas?

**Comment by jannyHou** [comment]
@jmereaux I tried with your use case, and `Vehicle.find({where: {personId: null}})` works.

I am closing this issue since problem solved. Please feel free to reopen it if you still have questions.
