### ISSUE TITLE
$regex requires an equality operator as the basis of the query

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#77]
From cloudant document page: https://docs.cloudant.com/cloudant_query.html#sort-syntax
>You cannot use combination or array logical operators such as $regex as the basis of a query when using indexes of type json. Only equality operators such as $eq, $gt, $gte, $lt, and $lte (but not $ne) can be used as the basis of a query for json indexes.

```json
{
  "selector": {
    "afieldname": {
      "$regex": "^A"
    }
  }
}
```
would result in error ` error: "no_usable_index", reason: "There is no operator in this selector can used with an index."`

>A solution is to use an equality operator as the basis of the query. You can add a ‘null’ or always true expression as the basis of the query. For example, you could first test that the document has an _id value:
"_id": { "$gt": null }
This expression is always true, enabling the remainder of the selector expression to be applied.

So build selector like:

```json
{
  "selector": {
    "_id": { 
      "$gt": null 
    },
    "afieldname": {
      "$regex": "^A"
    }
  }
}
```

**Comment by jannyHou** [comment]
Fix in PR https://github.com/strongloop/loopback-connector-cloudant/pull/81
**Please note that the fix may not work when a condition for `_id` also exists in the filter.**
- If the `_id` filter contains equality operator then good, `$regex` will be applied. 
- While if not, it's hard on connector side to add another equality filter without affecting the returned result. In this case,  user will need to include a custom equality filter to "boot" `$regex` in cloudant.

**Comment by kjdelisle** [comment]
@jannyHou You'll be writing the documentation for this change as a part of this task.

**Comment by kjdelisle** [comment]
Documented. Closing.
