### ISSUE TITLE
Connector assumes username and subdomain should be same

### ISSUE THREAD

**Issue by ufuf** [strongloop/loopback-connector-cloudant#79]
### Bug or feature request

- [ ] Bug
- [X] Feature request

### Description of feature (or steps to reproduce if bug)

Connector assumes that username and cloudant url subdomain is same. But I do not have to use the admin credentials with full access.
I should be able to create a restricted user for connection through cloudant dashboard and that can also be used by the connector.
Right now this causes an invalid url error because it just copies username as subdomain.

### Link to sample repo to reproduce issue (if bug)

Create a permission for a new user with just read and write access and try adding datasource with these credentials.

### Expected result

Datasource should be connected to cloudant without any errors.

### Actual result (if bug)

Throws invalid url error.

### Additional information (Node.js version, LoopBack version, etc)

I tried this with connector@1.1.0 and cloudant@1.7.0

**Comment by jannyHou** [comment]
I believe it's same as https://github.com/strongloop/loopback-connector-cloudant/issues/68

**Comment by ssh24** [comment]
@ufuf When you have another user that does not have the **admin** role, but has some sort of **read, create, etc...** permission on the database, you can use the `CLOUDANT_URL` env variable to set the url or set the url on the datasource config as well. For more information, please read the docs on how to use [`url vs username vs password`](https://github.com/strongloop/loopback-connector-cloudant#url-vs-username--password).

Closing this issue, feel free to reopen if you have any questions.

**Comment by ufuf** [comment]
@ssh24 I updated the connectors but still getting the error.
My configuration is cloudant@1.8.0, loopback@2.38.3, loopback-connector-cloudant@1.2.3
And my config is attached.
<img width="1012" alt="screen shot 2017-06-06 at 20 33 01" src="https://user-images.githubusercontent.com/4348233/26843347-9fab78f6-4af8-11e7-964a-c3268bda03a3.png">

**Comment by ssh24** [comment]
Sorry, @ufuf I thought the fix was already in 1.x. Reopening this issue and backporting the fix. Thank you for your patience.

**Comment by ssh24** [comment]
@ufuf Ignore my previous comment. Tried reproducing and the fix is already in 1.x.

Did you check the `_admin` role for the user you are giving the access to? Please check off the `_admin` role and try again.

**Comment by ufuf** [comment]
@ssh24 it seems off. My permissions screen is like this:
<img width="860" alt="screen shot 2017-06-08 at 13 11 19" src="https://user-images.githubusercontent.com/4348233/26923868-310269a0-4c4c-11e7-8334-a3f3e76327e6.png">

**Comment by ssh24** [comment]
@ufuf You need to check off the `_admin` role to the user in blue.

**Comment by ufuf** [comment]
@ssh24 it is already off. only reader and writer attributes are selected.

**Comment by ssh24** [comment]
Sorry, I meant to check it on.

**Comment by ufuf** [comment]
I checked it on. Right now all the checkboxes are selected. But in Api Designer I am still getting error while trying to connect.
<img width="589" alt="screen shot 2017-06-08 at 14 17 08" src="https://user-images.githubusercontent.com/4348233/26926189-5a040ea4-4c55-11e7-90b1-f113d6c2c0df.png">

**Comment by ssh24** [comment]
@ufuf I can reproduce the above issue. But it is a apic bug rather than cloudant. I will file a bug in apic end to get this looked into asap.

In order to know it is not a cloudant bug, you can create a boot script and run it. It works with the custom user with `_admin` privileges.

`/server/boot/script.js`
```javascript
'use strict';
var async = require('async');
var _ = require('lodash');
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.cloudantDS;
  var Car = app.models.Car;

  db.automigrate(function(err) {
    if (err) throw err;
    Car.create([{Model: 'Toyota', Year: 2005}, {Model: 'Audi', Year: 2014}],
  function(err, result) {
    if (err) throw err;
    console.log('Create: ' + JSON.stringify(result));
  });
  });
};
```

Hope this helps you.

Also, thank you for helping us finding a bug on the product side. :)

**Comment by ufuf** [comment]
@ssh24 Thanks for the info. So I will wait for the product bugfix :)
Thanks for your help.
