### ISSUE TITLE
Support second level property(relation property) filter in cloudant

### ISSUE THREAD

**Issue by jmereaux** [strongloop/loopback-connector-cloudant#8]
Let's take an example:

```
{
  "name": "Person",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "name",
      "required": true
    },
  },
  "validations": [],
  "relations": {
    "vehicle": {
      "type": "hasOne",
      "model": "Vehicle"
    }
  }
  "acls": [],
  "methods": {}
}

{
  "name": "Vehicle",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "brand": {
      "type": "string",
      "required": true
    },
    "name": {
      "type": "string",
      "required": true
    },
  },
  "validations": [],
  "relations": {
    "owner": {
      "type": "belongsTo",
      "model": "Person"
    }
  },
  "acls": [],
  "methods": {}
}
```

Is there any way to fetch with a simple query/filter, all the persons who have a vehicle of brand XXX ?

**Comment by rexpie** [comment]
I think the purpose of the views in design documents are supposed to do just that.

**Comment by tonyffrench** [comment]
@jmereaux: You could try something like:

 `curl -g 'http://0.0.0.0:3000/api/Vehicles?filter[where][brand]=D&filter[include]=owners` 

If you want to go in the other direction, you can apply filters to related models, see https://docs.strongloop.com/display/public/LB/Include+filter

**Comment by tonyffrench** [comment]
The datasource-juggler test suite might have some useful examples:
strongloop/loopback-datasource-juggler/test/{include.test.js,relations.test.js}

**Comment by jmereaux** [comment]
@rexpie: Could you please elaborate? I'm afraid I'm not familiar with "views in design documents". Thanks

**Comment by jmereaux** [comment]
@tonyffrench: Thanks a lot for your help.

I looked at the huge test files, but unfortunately did not find what I was looking for.

As far as I understand, the curl query you provided enables to fetch all the vehicles with brand 'D' and to include their owners. Therefore, I would have to iterate on the resulting vehicles and then to collect their owners.
In case the 'vehicle' relation on Person became a hasMany (a person could have multiple vehicles), if we were using your curl query, we would also have to filter duplicate owners out.

What I'd rather like to do is a query like:
Person.find({where: {vehicle.brand : 'D'}})
Is it possible somehow?

**Comment by jannyHou** [comment]
@jmereaux loopback doesn't support a filter on second level property, eg: `vehicle.brand`, now I am afraid you have to collect the personIds and remove duplicate manually.

We are working on supporting the feature in some databases like mongodb:
feature issue see: https://github.com/strongloop/loopback/issues/517
mongodb pr see: https://github.com/strongloop/loopback-connector-mongodb/pull/301


I filed an issue in cloudant to support it: https://github.com/strongloop/loopback-connector-cloudant/issues/57

---
Labelled this issue as a feature:

Use case:
`Person` hasMany `Vehicle`.
**We want to support** a filter like 
```js
Person.find({
  where: {
    vehicle.brand : 'D'  // second level property
  }
})
```

**Comment by jannyHou** [comment]
I am closing this PR and let's keep discussion in https://github.com/strongloop/loopback/issues/517. Thanks!
